### ISSUE TITLE
would be nice to get 1.0 final as it is out now

### ISSUE THREAD

**Issue by rburgst** [robertwtucker/docker-realm-object-server#1]
still is the beta AFAICS

**Comment by robertwtucker** [comment]
Thanks for the message! Looks like I just missed the updated package when I checked the other day. It now runs 1.0.0-164.

```
❯ docker exec -it realm bash
root@44a6f418c06e:/# apt search realm
Sorting... Done
Full Text Search... Done
realm-object-server-developer/now 1.0.0-164 amd64 [installed,local]
  Realm Object Server - Developer Edition
```

I will also look into a strategy for triggering updates when new packages are pushed.
